### ISSUE TITLE
Pregunta sobre el origen de el léxico de palabras y sentimientos asociados

### ISSUE THREAD

**Issue by skqr** [d4tagirl/uruguayan_parliamentary_session_diary#1]
Hola!

Estamos haciendo un curso de data sci en Buenos Aires y mirando el código de tu trabajo nos preguntamos con una compañera: cuál es el origen de la tabla SpanishSentimentLexicons/fullStrengthLexicon.txt? La generás en alguna parte del código? Cuáles son sus headers?

Gracias!

**Comment by d4tagirl** [comment]
Hola! 

El lexicon que uso es este: http://web.eecs.umich.edu/~mihalcea/downloads/SpanishSentimentLexicons.tar.gz, que incluye dos lexicones: uno fullStrength y uno mediumStrength. En ningún lugar encontré mucha documentación al respecto, y es una tabla sin headers. Me quedé con la primera columna que describe sentimiento, porque la segunda estaba muy poco poblada. 

No hice un análisis profundo del lexicon, pero tiene evidentes limitaciones:
  * Tiene muy pocos términos (476 positivas de 871 en total)
  * La mayoría (si no todos) los adjetivos que considera son masculinos

Mucha suerte en el trabajo 🍀

**Comment by d4tagirl** [comment]
Ahí le agregué más comentarios al código y lo dejé más prolijo. Además le agregué un Readme que incluye información del Lexicón. 

Muchas gracias por llamarme la atención con esas cosas! Y gracias por el interés 😃

**Comment by skqr** [comment]
Ea, muchísimas gracias a vos! Mil disculpas por la demora en contestar - las notificaciones de GitHub y yo nos entendemos más bien poco 😛

**Comment by d4tagirl** [comment]
No hay problema! Mucha suerte!
